### ISSUE TITLE
Colors for modeline process section

### ISSUE THREAD

**Issue by sebasmonia** [vallyscode/cloud-theme#2]
You can see here the colors for the eglot process lighters are really hard to read:

![image](https://user-images.githubusercontent.com/1651857/74770467-8f63e400-5249-11ea-9655-ee62fea619db.png)

Ditto for compilation mode:

![image](https://user-images.githubusercontent.com/1651857/74770563-b7ebde00-5249-11ea-96a3-74ca2135c7a6.png)

Not sure how much of this is on cloud-theme and how much should be modified by eglot/customizing compilation. Compilation being built in, it would be nice to provide an adjustment OOTB.

Thank you!!!

**Comment by vallyscode** [comment]
All is doable in scope of cloud-theme, I will make adjustments tomorrow

**Comment by vallyscode** [comment]
Changes applied, so closing
