### ISSUE TITLE
xref-file-header is hard to read

### ISSUE THREAD

**Issue by sebasmonia** [vallyscode/cloud-theme#3]
Hi again, sorry to be a bother :)

I think the last change was detrimental for xref mode, see below:

![image](https://user-images.githubusercontent.com/1651857/75060509-2fb14700-549c-11ea-88dd-58bb762519a4.png)

I did `describe-face` and turns out it inherits from `compilation-info` which is why I think the last change has something to do.

Thank you for fixing the modeline!

**Comment by vallyscode** [comment]
Hi, changed color for xref, now xref header color is same as in dired.
This is how it looks now:
![screenshot_xref](https://user-images.githubusercontent.com/5089096/75065854-9c9b0000-54e1-11ea-8e9a-62adb9f65fdc.png)

**Comment by sebasmonia** [comment]
Awesome, thank you! Looks great.
My local fix was a lot worse because I have no sense of aesthetics LOL.
